# the above tag defines encoding for this document and is for Python 2.x compatibility

import re

regex = r"[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+"

test_str = ("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n"
	"<html>\n"
	"<head>\n"
	"  <meta http-equiv=\"Content-Type\"\n"
	" content=\"text/html; charset=UTF-8\">\n"
	"  <title>Vendor Round Table (Page 1) / Announcements / Evolution\n"
	"Community Forums</title>\n"
	"  <link rel=\"shortcut icon\" href=\"favicon.ico\">\n"
	"<!--[if lte IE 6]><script type=\"text/javascript\" src=\"style/imports/minmax.js\"></script><![endif]-->\n"
	"  <link rel=\"stylesheet\" type=\"text/css\"\n"
	" href=\"index.css\" media=\"all\">\n"
	"</head>\n"
	"<body>\n"
	"<div id=\"punviewtopic\" class=\"pun\">\n"
	"<div class=\"top-box\">\n"
	"<div><!-- Top Corners --></div>\n"
	"</div>\n"
	"<div class=\"punwrap\">\n"
	"<div id=\"brdheader\" class=\"block\">\n"
	"<div class=\"box\">\n"
	"<div id=\"brdtitle\" class=\"inbox\"><img\n"
	" title=\"Evolution Community Forums\"\n"
	" alt=\"Evolution Community Forums\" src=\"logo_forum.png\">\n"
	"<div id=\"brddesc\"></div>\n"
	"</div>\n"
	"<div id=\"brdmenu\" class=\"inbox\">\n"
	"<ul>\n"
	"  <li id=\"navindex\" class=\"isactive\"><a\n"
	" href=\"/index.php\">Index</a></li>\n"
	"  <li id=\"navregister\"><a href=\"/register.php\">Register</a></li>\n"
	"  <li id=\"navlogin\"><a href=\"/login.php\">Login</a></li>\n"
	"</ul>\n"
	"</div>\n"
	"<div id=\"brdwelcome\" class=\"inbox\">\n"
	"<p class=\"conl\">You are not logged in.</p>\n"
	"<div class=\"clearer\"></div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"brdmain\">\n"
	"<div class=\"linkst\">\n"
	"<div class=\"inbox crumbsplus\">\n"
	"<ul class=\"crumbs\">\n"
	"  <li><a href=\"/index.php\">Index</a></li>\n"
	"  <li><span>&raquo;&nbsp;</span><a\n"
	" href=\"/viewforum.php?id=3\">Announcements</a></li>\n"
	"  <li><span>&raquo;&nbsp;</span><strong><a\n"
	" href=\"/viewtopic.php?id=22410\">Vendor\n"
	"Round Table</a></strong></li>\n"
	"</ul>\n"
	"<div class=\"pagepost\">\n"
	"<p class=\"pagelink conl\"><span class=\"pages-label\">Pages:\n"
	"</span><strong class=\"item1\">1</strong> <a\n"
	" href=\"/viewtopic.php?id=22410&amp;p=2\">2</a>\n"
	"<a href=\"/viewtopic.php?id=22410&amp;p=3\">3</a>\n"
	"<span class=\"spacer\">&hellip;</span> <a\n"
	" href=\"/viewtopic.php?id=22410&amp;p=43\">43</a>\n"
	"<a rel=\"next\" href=\"/viewtopic.php?id=22410&amp;p=2\">Next</a></p>\n"
	"</div>\n"
	"<div class=\"clearer\"></div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p198998\"\n"
	" class=\"blockpost rowodd firstpost blockpost1\">\n"
	"<h2><span><span class=\"conr\">#1</span> <a\n"
	" href=\"/viewtopic.php?pid=198998#p198998\">2014-09-02\n"
	"01:58:39</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid1\">Verto</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Administrator</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"3.jpg\" alt=\"\"\n"
	" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-01-11</span></dd>\n"
	"  <dd><span>Posts: 1,234</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>By popular demand we now have a Vendor Round Table. Only\n"
	"requirement is you must hold a vendor account on evolution market.\n"
	"Vendors will also receive a \"Vendor\" tag on the forums.</p>\n"
	"<p>Post in this thread for access permissions.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>/profile/1/pgp</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199001\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#2</span> <a\n"
	" href=\"/viewtopic.php?pid=199001#p199001\">2014-09-02\n"
	"02:01:24</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">patriotcow</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>Registered: 2014-07-09</span></dd>\n"
	"  <dd><span>Posts: 134</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access please</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199047\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#3</span> <a\n"
	" href=\"/viewtopic.php?pid=199047#p199047\">2014-09-02\n"
	"03:17:28</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">XXXDVDXXX</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Banned</strong></dd>\n"
	"  <dd><span>From: ON Top bigrock brother</span></dd>\n"
	"  <dd><span>Registered: 2014-08-07</span></dd>\n"
	"  <dd><span>Posts: 297</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Edit time:</p>\n"
	"<p class=\"postedit\"><em>Last edited by XXXDVDXXX\n"
	"(2014-09-06 05:17:50)</em></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199084\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#4</span> <a\n"
	" href=\"/viewtopic.php?pid=199084#p199084\">2014-09-02\n"
	"03:44:53</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">bitbybit</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"2052.jpg\"\n"
	" alt=\"\" height=\"90\" width=\"71\"></dd>\n"
	"  <dd><span>From: 2043</span></dd>\n"
	"  <dd><span>Registered: 2014-02-23</span></dd>\n"
	"  <dd><span>Posts: 860</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>access please</p>\n"
	"<p class=\"postedit\"><em>Last edited by bitbybit\n"
	"(2014-09-02 04:14:54)</em></p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>my btc beness /profile/7937</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199094\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#5</span> <a\n"
	" href=\"/viewtopic.php?pid=199094#p199094\">2014-09-02\n"
	"03:57:46</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">onionseller</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"4445.png\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-04-17</span></dd>\n"
	"  <dd><span>Posts: 458</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access?</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><span style=\"color: red;\"><strong>/store/25317</strong></span>\n"
	"<br>\n"
	"<span style=\"color: rgb(245, 184, 0);\">Level 3</span><br>\n"
	"<span style=\"color: green;\">100% feedback</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199099\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#6</span> <a\n"
	" href=\"/viewtopic.php?pid=199099#p199099\">2014-09-02\n"
	"04:02:30</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Trippyy</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"7639.jpg\"\n"
	" alt=\"\" height=\"50\" width=\"90\"></dd>\n"
	"  <dd><span>From: Psychedelic</span></dd>\n"
	"  <dd><span>Registered: 2014-06-24</span></dd>\n"
	"  <dd><span>Posts: 2,073</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access? I have a vendors account.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>~ You can't separate peace from freedom because no one can be\n"
	"at peace unless they have their freedom ~</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199103\" class=\"blockpost rowodd\">\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postright\">\n"
	"<div class=\"postmsg\">\n"
	"<p>I would love access, thank you.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>XMPP: skypeman@jabbim.cz - OTR ONLY<br>\n"
	"<strong><span style=\"color: rgb(230, 126, 34);\">★\n"
	"Misc. Account Shop ★1$★</span></strong>: <strong>/viewtopic.php?id=22305</strong><br>\n"
	"<strong><span style=\"color: rgb(192, 57, 43);\">★\n"
	"Netflix Account Shop ★1$★</span></strong>: <strong>/viewtopic.php?pid=70160</strong><br>\n"
	"<strong><span style=\"color: rgb(142, 68, 173);\">★\n"
	"Spotify Account Shop ★1$★</span></strong>: <strong>/viewtopic.php?id=8614</strong></p>\n"
	"</div>\n"
	"</div>\n"
	"Re: Vendor Round Table\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199120\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#8</span> <a\n"
	" href=\"/viewtopic.php?pid=199120#p199120\">2014-09-02\n"
	"04:48:25</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">sonics</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>Registered: 2014-01-21</span></dd>\n"
	"  <dd><span>Posts: 346</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>access please</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>ICQ: 667545775 OTR Only | Jabber: sonics@creep.im</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199122\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#9</span> <a\n"
	" href=\"/viewtopic.php?pid=199122#p199122\">2014-09-02\n"
	"04:52:36</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">anonpsychosis</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>From: Somewhere under the sea</span></dd>\n"
	"  <dd><span>Registered: 2014-01-18</span></dd>\n"
	"  <dd><span>Posts: 449</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access Please<br>\n"
	"Thanks</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>PM me for my ICQ and Jabber OTR Only<br>\n"
	"pgp public key is on my marketplace profile</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199124\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#10</span> <a\n"
	" href=\"/viewtopic.php?pid=199124#p199124\">2014-09-02\n"
	"04:59:27</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Diamondzz</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"10514.png\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>From: Bel-Air, Los Angeles</span></dd>\n"
	"  <dd><span>Registered: 2014-08-07</span></dd>\n"
	"  <dd><span>Posts: 394</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access would be amazing sir <img src=\"smile.png\"\n"
	" alt=\"smile\" height=\"15\" width=\"15\"></p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong><span style=\"color: Green;\">Visit\n"
	"My Store! The Diamond Supply</span></strong> <ins>/store/99923</ins><br>\n"
	"<strong><span style=\"color: Green;\">Get Anything You\n"
	"Want for FREE [VOUCHED, EASY &amp; NO CARDING]</span></strong>\n"
	"<ins>/listing/76079</ins><br>\n"
	"<strong><span style=\"color: Blue;\">ICQ: 661711597</span></strong></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199152\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#11</span> <a\n"
	" href=\"/viewtopic.php?pid=199152#p199152\">2014-09-02\n"
	"05:37:33</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Diamondzz</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"10514.png\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>From: Bel-Air, Los Angeles</span></dd>\n"
	"  <dd><span>Registered: 2014-08-07</span></dd>\n"
	"  <dd><span>Posts: 394</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Great idea but just some feedback: I think the forum would\n"
	"look cleaner if the green name was only visible next to ones post and\n"
	"not actually next to their threads when looking at an entire forum.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong><span style=\"color: Green;\">Visit\n"
	"My Store! The Diamond Supply</span></strong> <ins>/store/99923</ins><br>\n"
	"<strong><span style=\"color: Green;\">Get Anything You\n"
	"Want for FREE [VOUCHED, EASY &amp; NO CARDING]</span></strong>\n"
	"<ins>/listing/76079</ins><br>\n"
	"<strong><span style=\"color: Blue;\">ICQ: 661711597</span></strong></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199160\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#12</span> <a\n"
	" href=\"/viewtopic.php?pid=199160#p199160\">2014-09-02\n"
	"05:44:36</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">GetBTC</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"3732.jpg\"\n"
	" alt=\"\" height=\"90\" width=\"69\"></dd>\n"
	"  <dd><span>Registered: 2014-03-31</span></dd>\n"
	"  <dd><span>Posts: 978</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Great idea. Access please.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong>HEY YOU VISIT MY LEVEL 3 BADASS STORE</strong>\n"
	"- /store/20600<br>\n"
	"<span style=\"color: rgb(255, 0, 0);\"><strong>PREMIUM\n"
	"GUIDES</strong></span><br>\n"
	"<strong>PP (or VCC) to BTC method</strong> [HOT] -\n"
	"/listing/9610<br>\n"
	"<strong>How to Card Virwox</strong> [NOOB GOLD] -\n"
	"/listing/21512</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199167\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#13</span> <a\n"
	" href=\"/viewtopic.php?pid=199167#p199167\">2014-09-02\n"
	"06:03:52</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Epan</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"5141.jpg\"\n"
	" alt=\"\" height=\"68\" width=\"78\"></dd>\n"
	"  <dd><span>From: EU</span></dd>\n"
	"  <dd><span>Registered: 2014-05-04</span></dd>\n"
	"  <dd><span>Posts: 364</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Nice! Acces please</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong><span class=\"bbu\">Store:</span></strong>\n"
	"/store/28077</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199185\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#14</span> <a\n"
	" href=\"/viewtopic.php?pid=199185#p199185\">2014-09-02\n"
	"06:31:00</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">south-storm</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"10690.jpg\"\n"
	" alt=\"\" height=\"69\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-08-09</span></dd>\n"
	"  <dd><span>Posts: 32</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>access please..!!!</p>\n"
	"<p>My Store link :-&nbsp;\n"
	"/store/21102</p>\n"
	"<p class=\"postedit\"><em>Last edited by south-storm\n"
	"(2014-09-02 06:33:45)</em></p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>visit my store :- <span style=\"color: blue;\">/store/21102</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199190\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#15</span> <a\n"
	" href=\"/viewtopic.php?pid=199190#p199190\">2014-09-02\n"
	"06:42:44</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Lenin_Cat</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"3445.png\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-03-24</span></dd>\n"
	"  <dd><span>Posts: 587</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Please <img src=\"smile.png\" alt=\"smile\"\n"
	" height=\"15\" width=\"15\"></p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong>Make weapons section! <img src=\"sad.png\"\n"
	" alt=\"sad\" height=\"15\" width=\"15\"></strong><br>\n"
	"Retired.</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199232\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#16</span> <a\n"
	" href=\"/viewtopic.php?pid=199232#p199232\">2014-09-02\n"
	"07:58:53</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Voxis_Team</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>From: voxis_team@lsd-25.ru</span></dd>\n"
	"  <dd><span>Registered: 2014-08-08</span></dd>\n"
	"  <dd><span>Posts: 170</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access please.<br>\n"
	"Thank you.</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>Voxis Platform OFFICIAL Store:\n"
	"/store/100765<br>\n"
	"PGP Public Key:\n"
	"https://pgp.mit.edu/pks/lookup?op=vindex&amp;search=0x9BE0ED6DEDC3C7B3<br>\n"
	"OFFICIAL Jabber address: voxis_team@lsd-25.ru<br>\n"
	"We DON'T have ICQ#.</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199278\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#17</span> <a\n"
	" href=\"/viewtopic.php?pid=199278#p199278\">2014-09-02\n"
	"09:23:02</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid4\">keysagogo</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Member</strong></dd>\n"
	"  <dd><span>Registered: 2014-01-14</span></dd>\n"
	"  <dd><span>Posts: 370</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>It is required that the username here in the forums and the\n"
	"one in EVO market are the same? Cuz my store's account is different\n"
	"than my buyer account (this one).</p>\n"
	"<p>Otherwise, access please <img src=\"tongue.png\"\n"
	" alt=\"tongue\" height=\"15\" width=\"15\"></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199287\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#18</span> <a\n"
	" href=\"/viewtopic.php?pid=199287#p199287\">2014-09-02\n"
	"09:38:45</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">Sportlife</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"3259.jpg\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-03-21</span></dd>\n"
	"  <dd><span>Posts: 577</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access please.<br>\n"
	"Thanks!</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><ins> ★★★&nbsp; BUY COUNTERFEIT &euro;20\n"
	"BILLS!!! ★★★ </ins>&nbsp;\n"
	"/listing/7755<br>\n"
	"<ins> ★★★&nbsp; MDMA crystals 1gram for &euro;14 - Only\n"
	"this week ★★★ </ins>&nbsp;\n"
	"/listing/17512</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199288\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#19</span> <a\n"
	" href=\"/viewtopic.php?pid=199288#p199288\">2014-09-02\n"
	"09:41:18</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid4\">Adhrann</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Member</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"6707.jpg\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>From: Mofoland</span></dd>\n"
	"  <dd><span>Registered: 2014-06-06</span></dd>\n"
	"  <dd><span>Posts: 863</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Great idea, thanks!</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>ICQ OTR: 668122485&nbsp; &nbsp;XMPP: adhrann@jabbim.cz<br>\n"
	"'Don't go around saying the world owes you a living. The world owes you\n"
	"shit. It was here first'.</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199297\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#20</span> <a\n"
	" href=\"/viewtopic.php?pid=199297#p199297\">2014-09-02\n"
	"09:52:25</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">FOX-15</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"5199.jpg\"\n"
	" alt=\"\" height=\"65\" width=\"90\"></dd>\n"
	"  <dd><span>From: Italy &amp; Slovenia</span></dd>\n"
	"  <dd><span>Registered: 2014-05-06</span></dd>\n"
	"  <dd><span>Posts: 6</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access Please<br>\n"
	"Thank you in advance <img src=\"wink.png\" alt=\"wink\"\n"
	" height=\"15\" width=\"15\"></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199301\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#21</span> <a\n"
	" href=\"/viewtopic.php?pid=199301#p199301\">2014-09-02\n"
	"09:58:15</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">jabberwocky</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"6334.jpg\"\n"
	" alt=\"\" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>From: Wonderland</span></dd>\n"
	"  <dd><span>Registered: 2014-05-29</span></dd>\n"
	"  <dd><span>Posts: 53</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access please</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>NOT GOVERNMENT/POLICE/COURT, ONLY KARMA. KARMA AND A LITTLE\n"
	"WEED.<br>\n"
	"ICQ + OTR : 669977633 | jabberwocky@jabber.systemli.org<br>\n"
	"<ins>Premium BTC MasterCard :\n"
	"/listing/91238</ins></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199305\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#22</span> <a\n"
	" href=\"/viewtopic.php?pid=199305#p199305\">2014-09-02\n"
	"10:05:15</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid4\">MrMouse</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Banned</strong></dd>\n"
	"  <dd class=\"postavatar\"><img src=\"14.jpg\" alt=\"\"\n"
	" height=\"90\" width=\"90\"></dd>\n"
	"  <dd><span>Registered: 2014-01-14</span></dd>\n"
	"  <dd><span>Posts: 472</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access Please!</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><em>Professional Services by Mr. Mouse-\n"
	"http://pastebin.com/xLY8TSzS</em></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199329\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#23</span> <a\n"
	" href=\"/viewtopic.php?pid=199329#p199329\">2014-09-02\n"
	"10:30:47</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">lokmannen</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>Registered: 2014-02-09</span></dd>\n"
	"  <dd><span>Posts: 365</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>Access please</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p>Offering Amazon refund service US/UK<br>\n"
	"Listing: /listing/5812</p>\n"
	"<p>ICQ: 653637238</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199354\" class=\"blockpost roweven\">\n"
	"<h2><span><span class=\"conr\">#24</span> <a\n"
	" href=\"/viewtopic.php?pid=199354#p199354\">2014-09-02\n"
	"11:17:32</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">moka</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>From: mcdonald's breakfast</span></dd>\n"
	"  <dd><span>Registered: 2014-01-22</span></dd>\n"
	"  <dd><span>Posts: 1,671</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>access please !</p>\n"
	"</div>\n"
	"<div class=\"postsignature postmsg\">\n"
	"<hr>\n"
	"<p><strong>MonkeyBusiness </strong><ins>♛</ins>\n"
	"| <span style=\"color: rgb(163, 165, 170);\">http://pastebin.com/Y3vbhayZ</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><strong>Online</strong></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div id=\"p199436\" class=\"blockpost rowodd\">\n"
	"<h2><span><span class=\"conr\">#25</span> <a\n"
	" href=\"/viewtopic.php?pid=199436#p199436\">2014-09-02\n"
	"12:38:52</a></span></h2>\n"
	"<div class=\"box\">\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postbody\">\n"
	"<div class=\"postleft\">\n"
	"<dl>\n"
	"  <dt><strong><span class=\"gid8\">gonein60</span></strong></dt>\n"
	"  <dd class=\"usertitle\"><strong>Vendor</strong></dd>\n"
	"  <dd><span>Registered: 2014-06-16</span></dd>\n"
	"  <dd><span>Posts: 30</span></dd>\n"
	"</dl>\n"
	"</div>\n"
	"<div class=\"postright\">\n"
	"<h3>Re: Vendor Round Table</h3>\n"
	"<div class=\"postmsg\">\n"
	"<p>I'd like to get access aswell, thank you.</p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"inbox\">\n"
	"<div class=\"postfoot clearb\">\n"
	"<div class=\"postfootleft\">\n"
	"<p><span>Offline</span></p>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"postlinksb\">\n"
	"<div class=\"inbox crumbsplus\">\n"
	"<div class=\"pagepost\">\n"
	"<p class=\"pagelink conl\"><span class=\"pages-label\">Pages:\n"
	"</span><strong class=\"item1\">1</strong> <a\n"
	" href=\"/viewtopic.php?id=22410&amp;p=2\">2</a>\n"
	"<a href=\"/viewtopic.php?id=22410&amp;p=3\">3</a>\n"
	"<span class=\"spacer\">&hellip;</span> <a\n"
	" href=\"/viewtopic.php?id=22410&amp;p=43\">43</a>\n"
	"<a rel=\"next\" href=\"/viewtopic.php?id=22410&amp;p=2\">Next</a></p>\n"
	"</div>\n"
	"<ul class=\"crumbs\">\n"
	"  <li><a href=\"/index.php\">Index</a></li>\n"
	"  <li><span>&raquo;&nbsp;</span><a\n"
	" href=\"/viewforum.php?id=3\">Announcements</a></li>\n"
	"  <li><span>&raquo;&nbsp;</span><strong><a\n"
	" href=\"/viewtopic.php?id=22410\">Vendor\n"
	"Round Table</a></strong></li>\n"
	"</ul>\n"
	"<br>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"</div>\n"
	"<div class=\"end-box\">\n"
	"</div>\n"
	"</div>\n"
	"</body>\n"
	"</html>")

matches = re.finditer(regex, test_str, re.MULTILINE | re.IGNORECASE)

for matchNum, match in enumerate(matches):
    matchNum = matchNum + 1
    
    print ("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum = matchNum, start = match.start(), end = match.end(), match = match.group()))
    
    for groupNum in range(0, len(match.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = match.start(groupNum), end = match.end(groupNum), group = match.group(groupNum)))
